// This file is auto-generated by @hey-api/openapi-ts

/**
 * Dog
 * Information about a dog
 */
export type Dog = {
  id: string;
  name: string;
  awesomeness: number;
  image?: string;
};

export type GetAllDogsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/dogs';
};

export type GetAllDogsErrors = {
  /**
   * Unauthorized
   */
  401: unknown;
};

export type GetAllDogsResponses = {
  /**
   * OK
   */
  200: Array<Dog>;
};

export type GetAllDogsResponse = GetAllDogsResponses[keyof GetAllDogsResponses];

export type ClientOptions = {
  baseUrl: 'http://localhost:3000' | (string & {});
};
