// This file is auto-generated by @hey-api/openapi-ts

export type Dimensions = {
  width: number;
  height: number;
  depth: number;
};

export type Review = {
  rating: number;
  comment: string;
  date: string;
  reviewerName: string;
  reviewerEmail: string;
};

export type Meta = {
  createdAt: string;
  updatedAt: string;
  barcode: string;
  qrCode: string;
};

/**
 * Product
 * Information about a product
 */
export type Product = {
  id: number;
  title: string;
  description: string;
  category: string;
  price: number;
  discountPercentage: number;
  rating: number;
  stock: number;
  tags?: Array<string>;
  brand: string;
  sku?: string;
  weight?: number;
  dimensions?: Dimensions;
  warrantyInformation?: string;
  shippingInformation?: string;
  availabilityStatus?: string;
  reviews: Array<Review>;
  returnPolicy?: string;
  minimumOrderQuantity?: number;
  meta?: Meta;
  thumbnail: string;
  images?: Array<string>;
};

export type GetAllProductsData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Number of items to return
     */
    limit?: number;
  };
  url: '/products';
};

export type GetAllProductsErrors = {
  /**
   * Invalid status value
   */
  400: {
    message?: string;
  };
  /**
   * Unexpected error
   */
  default: {
    message?: string;
  };
};

export type GetAllProductsError =
  GetAllProductsErrors[keyof GetAllProductsErrors];

export type GetAllProductsResponses = {
  /**
   * OK
   */
  200: {
    products?: Array<Product>;
    total?: number;
    skip?: number;
    limit?: number;
  };
};

export type GetAllProductsResponse =
  GetAllProductsResponses[keyof GetAllProductsResponses];

export type ClientOptions = {
  baseUrl: 'https://dummyjson.com' | (string & {});
};
